### ISSUE TITLE
local CLI and HTTP/3 with TLS

### ISSUE THREAD

**Issue by WafflyOwl1** [johannesschiessl/AI-Assistant#1]
I trust this message finds you well. I've been exploring your app and would like to seek clarification on the methods available for end-users or developers to access it.

Based on my understanding, the app can be accessed through the following means:

Local Access:
Desktop/Mobile UI
Command Line Interface (CLI)
Remote Access:
Web UI
HTTP/3 GET Requests to API Endpoints
Could you kindly provide more details on each of these access methods? For instance, what features are available through the desktop/mobile UI, CLI, and web UI? Additionally, are there any specific API endpoints that developers can leverage through HTTP/3 GET requests?

Understanding these access points will greatly assist in optimizing the user experience and help us make the most of the app's capabilities.

Thank you for your time and assistance. Looking forward to your guidance.

Best Regards,

WafflyOwl1

**Comment by johannesschiessl** [comment]
Hi @WafflyOwl1,

I appreciate your exploration of the application and your interest in understanding the available access methods. Currently, the application is only available through the Command Line Interface (CLI) for local access. Unfortunately, the Web UI is not available at this time.

For local access, the CLI provides a robust set of features to interact with the application efficiently. I'm planning to add support for a Web UI in future updates. This will be the primary focus for extending access beyond the CLI.

Regarding API access, I would like to clarify that we do not currently support HTTP/3 or HTTP GET requests. I appreciate your understanding as we refine and expand the capabilities of the application and apologize for any confusion in my previous communications.

If you have any further questions or need additional clarification, please feel free to reach out. Your insights are valuable as I continue to develop and improve the app.

Best regards,

Johannes Schießl
